[project]
name = "docs2static"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "colorlog>=6.10.1",
    "ipdb>=0.13.13",
    "requests>=2.32.5",
    "requests-cache>=1.2.1",
    "zensical>=0.0.17",
]
